# NumPy Indexing and Selection

Here we will discuss how to select elements or groups of elements from an array.

In [2]:
import numpy as np

In [3]:
#Creating sample array
arr=np.arange(0,21)

In [4]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [5]:
#Creating sample array
arr=np.arange(10,100,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [6]:
len(arr)

18

In [7]:
arr[-1]

np.int64(95)

In [8]:
#Get a value at an index
arr[9]

np.int64(55)

In [9]:
#Get values in a range
arr[1:11:2]

array([15, 25, 35, 45, 55])

### Filtering

In [ ]:
import numpy as np

In [10]:
# Filtering condition

arr=np.array([1,2,1010,4,108,18,71,610])
arr

array([   1,    2, 1010,    4,  108,   18,   71,  610])

In [11]:
arr<100

array([ True,  True, False,  True, False,  True,  True, False])

In [12]:
arr2=np.array([True,True,False,False])

In [13]:
np.where(arr2)

(array([0, 1]),)

In [14]:
arr[5]

np.int64(18)

In [15]:
arr[2]

np.int64(1010)

In [16]:
np.where(arr<100)# where function outputs index location of values
# meeting the condition

(array([0, 1, 3, 5, 6]),)

In [17]:
arr[np.where(arr>100)]=10

In [ ]:
arr

array([ 1,  2, 10,  4, 10, 18, 71, 10])

In [18]:
np.where(arr<100)

(array([0, 1, 2, 3, 4, 5, 6, 7]),)

In [19]:
np.where(arr==100)

(array([], dtype=int64),)

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. It is recommended to use the comma notation for clarity.

In [20]:
import numpy as np

In [21]:
11+12

23

In [22]:
a,b=int(input("Enter a number ")),int(input("Enter a number"))
print("sum of a and b is ",(a+b))

Enter a number 12
Enter a number12
sum of a and b is  24


In [23]:
arr_2d = np.array(([1,2,3],[12,15,18],[64,96,128]))

#Show
arr_2d

array([[  1,   2,   3],
       [ 12,  15,  18],
       [ 64,  96, 128]])

In [24]:
arr_2d[:,1]

array([ 2, 15, 96])

In [25]:
l1=[1,2,3,4,5]

In [26]:
l1[:3]

[1, 2, 3]

In [27]:
arr_2d[:2,:2]

array([[ 1,  2],
       [12, 15]])

In [31]:
arr3=np.arange(27).reshape(3,3,3)

In [32]:
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [33]:
arr3[1:,:2]

array([[[ 9, 10, 11],
        [12, 13, 14]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [34]:
arr_2d

array([[  1,   2,   3],
       [ 12,  15,  18],
       [ 64,  96, 128]])

In [38]:
arr_2d[1:,:3]

array([[ 12,  15,  18],
       [ 64,  96, 128]])

In [ ]:
arr_2d[1:,:2]

array([[12, 15],
       [64, 96]])

In [39]:
arr_2d.shape

(3, 3)

In [40]:
arr4=np.arange(15).reshape(3,5)

In [41]:
arr4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [42]:
arr4[1:,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [43]:
arr_2d

array([[  1,   2,   3],
       [ 12,  15,  18],
       [ 64,  96, 128]])

In [44]:
arr_2d[1]  # Indexing 2nd row

array([12, 15, 18])

In [45]:
arr_2d[:,2] # Indexing 3rd column

array([  3,  18, 128])

In [46]:
arr_2d[1:,1:]

array([[ 15,  18],
       [ 96, 128]])

In [47]:
arr_2d[1,1]

np.int64(15)

In [48]:
arr_2d

array([[  1,   2,   3],
       [ 12,  15,  18],
       [ 64,  96, 128]])

In [50]:
arr_2d[0:2]

array([[ 1,  2,  3],
       [12, 15, 18]])

In [51]:
# Indexing column
arr_2d[:,2]

array([  3,  18, 128])

In [52]:
arr5=np.arange(20).reshape(5,4)

In [53]:
arr5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [55]:
arr5[1:4,1:3]

array([[ 5,  6],
       [ 9, 10],
       [13, 14]])

In [57]:
arr5[1:4,1:3]

array([[ 5,  6],
       [ 9, 10],
       [13, 14]])

In [58]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[ 2,  3],
       [15, 18]])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [59]:
arr1=np.ones((10,10))
arr1.shape

(10, 10)

In [60]:
arr1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [61]:
for i in range(len(arr1)):
  arr1[i]=i

In [62]:
arr1

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [63]:
arr3=np.arange(27).reshape(3,3,3)

In [64]:
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [65]:
#Set up matrix
arr2d = np.zeros(arr1.shape)  # taking shape from an existing array

In [66]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [67]:
arr2d.shape

(10, 10)

In [68]:
no_of_rows=arr2d.shape[0]  # indexing the shape tuple

In [69]:
#Set up array

for i in range(no_of_rows):
    arr2d[i] = i

arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following

In [70]:
arr2d[[6,3,8]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [71]:
arr2d[:,[2,4,6,8]]

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.],
       [8., 8., 8., 8.],
       [9., 9., 9., 9.]])

In [72]:
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [73]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [75]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [76]:
arr2d[:,0]<4

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

# Happy Learning!